### ISSUE TITLE
Migrate to null-safety

### ISSUE THREAD

**Issue by abd99** [dmjones/flutter_lorem#1]
@dmjones, Can I help in migrating this package to null-safety? It is being used in one of the official Flutter samples and I'm working on migrating that.

Will create a PR soon if this sounds good.

**Comment by dmjones** [comment]
Sure! I’d be happy to merge a PR.

Which Flutter sample is using this, out of interest?

**Comment by abd99** [comment]
Thanks, @dmjones! I will start working on it.

A sample called [`Platform Design`](https://github.com/flutter/samples/tree/master/platform_design) is using it. It demonstrates how you can build a single Flutter app that adapts to the platform's design and gives you different UIs for Android and iOS.

**Comment by dmjones** [comment]
Thanks for the link.

PR now merged, released as (preview) version 2.0.0: https://pub.dev/packages/flutter_lorem/versions/2.0.0

**Comment by abd99** [comment]
Awesome. Thanks, @dmjones!
